apiVersion: v1
kind: Service
metadata:
  name: gotify-server-service
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: gotify-server
