apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      type: frontend
  template:
    metadata:
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/iamready
            #httpGet:
            #  path: /
            #  port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    type: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: dcorto.usw1.kubesail.io
    http:
      paths:
        - backend:
            serviceName: nginx-service
            servicePort: 80
